version: '3.8'
services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      - HUGGING_FACE_HUB_TOKEN=<secret>
    volumes:
      - /data/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "6602:8000"
    command: --model deepseek-ai/deepseek-coder-6.7b-instruct --enforce-eager  --dtype half --max-model-len 16384
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: all
              capabilities: [ gpu ]
              device_ids: [ "1" ] #, "2", "3" ] # only use 1st gpu
